### ISSUE TITLE
Would you like to remove the pytorch3d dependancy?

### ISSUE THREAD

**Issue by StarCycle** [CleanDiffuserTeam/CleanDiffuser#16]
Hi @pickxiguapi @ZibinDong,

Would you like to remove the pytorch3d dependancy and use 
[rotation_conversions.py](https://github.com/user-attachments/files/16086156/rotation_conversions.py.txt) instead?

`pytorch3d` is sometimes difficult to install...

Best,
StarCycle

**Comment by pickxiguapi** [comment]
Great alternative, why didn't I find it sooner! I'll update the related code this week to replace the dependencies related to `pytorch3d`. Thanks a lot！
