### ISSUE TITLE
Installation conflict of robosuite version and numba version 

### ISSUE THREAD

**Issue by RongXueZoe** [CleanDiffuserTeam/CleanDiffuser#2]
Hi. Thanks for your great work! 

Now I'm installing the dependencies by `pip install -r requirements.txt` and I run into an error as 
`ERROR: Cannot install -r requirements.txt (line 24) and numba==0.56.0 because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested numba==0.56.0
    robosuite 1.2.0 depends on numba<=0.53.1 and >=0.52.0`

Besides, due to gym 0.21.0 bugs `error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.`, I've downgraded setuptools and pip to setuptools==65.5.0 and pip==21, following https://github.com/openai/gym/issues/3176#issuecomment-1560026649.

**Comment by pickxiguapi** [comment]
Thank you for pointing that out! We found that it is very difficult to use a single `requirements.txt` to be compatible with diverse RL and IL environments, which has brought additional challenges to setting up the CleanDiffuser repo. We have decided to modify the installation tutorial for CleanDiffuser, splitting it into multiple `requirements.txt` corresponding to different environments. This updating and testing is expected to be completed **within this week**. We will keep this issue open until the updates are completed.

**Comment by RongXueZoe** [comment]
> Thank you for pointing that out! We found that it is very difficult to use a single `requirements.txt` to be compatible with diverse RL and IL environments, which has brought additional challenges to setting up the CleanDiffuser repo. We have decided to modify the installation tutorial for CleanDiffuser, splitting it into multiple `requirements.txt` corresponding to different environments. This updating and testing is expected to be completed **within this week**. We will keep this issue open until the updates are completed.

Great! Look forward to your update:) Thanks again.

**Comment by pickxiguapi** [comment]
Hi, we have fixed the environment incompatibility issue in the latest commit and provided a more user-friendly installation tutorial. I'll close this issue, feel free to re-open it if there are more issues!

**Comment by RongXueZoe** [comment]
> Hi, we have fixed the environment incompatibility issue in the latest commit and provided a more user-friendly installation tutorial. I'll close this issue, feel free to re-open it if there are more issues!

It works! Many thanks.
