### ISSUE TITLE
IDQLMlp lacks a activation layer between the last residual layer and the affine_out layer

### ISSUE THREAD

**Issue by ShirongLiu** [CleanDiffuserTeam/CleanDiffuser#26]
According to IDQL paper Appendix G, there is a activation layer between the last residual layer and the affine_out layer. Lack of this may reduce the performance in AntMaze.

**Comment by ZibinDong** [comment]
I'm sorry for that mistake. I've now updated the correct IDQLmlp in the main branch, and I'll retest IDQL's performance and update the report. Thanks again for checking it carefully. I've closed the issue, but feel free to reopen it if you have any more questions.
