### ISSUE TITLE
Gymnasium support question

### ISSUE THREAD

**Issue by skylooop** [CleanDiffuserTeam/CleanDiffuser#27]
I would like to thank authors for such a wonderful work and providing community with open-source easy to use unified diffusion in RL codebase.
I observed that there is dependency on `gym < 24.0`. Do author's plan to migrate to newer version of gym library (gymnasium) or there are some significant limitations on doing this? 
Thanks!

**Comment by pickxiguapi** [comment]
Hi skyloop, thanks for your interest! We must clarify that the various components of CleanDiffuser (e.g. Diffusion Models, NN and Sampling Methods) simply require only `pytorch` dependencies (and have loose version restrictions). Implementing various types of algorithms (Diffuser, DD...) based on CleanDiffuser also requires only such few dependencies. However, **most Diffusion for RL algorithms use the D4RL benchmark to verify performance**, which requires `gym` support. If you want to use a gymnasium-based environment, you just need to modify the `dataset` and `evaluation` part of the pipeline for a specific algorithm, they are decoupled from the algorithm implementation. Or you can follow the tutorials in cleanDiffuser to build your own pipeline!

**Comment by skylooop** [comment]
Thank you for reply! So if i want to use some custom environment, then it is enough to change `dataset` loader in pipeline script?

**Comment by pickxiguapi** [comment]
Sure! The single-file implementation of pipeline ensures that the matter is clear and simple, which is our core philosophy. You can understand that the training process of the diffusion models is supervised learning, so simply replacing it with your customized dataset during training is enough!

I will close the issue, and if you have more questions, feel free to reopen it!
