### ISSUE TITLE
Some compatibility issues after updating the main branch code.

### ISSUE THREAD

**Issue by StepNeverStop** [CleanDiffuserTeam/CleanDiffuser#29]
Hello, Author. 

I noticed that in commit 76f8142, there is some code logic that forcibly checks that the condition is not None. This seems to conflict with some algorithm calls in the pipelines, such as when instantiating the class `IDQLMlp` in `synther_d4rl_mujoco.py`. 

Should some compatibility adjustments be made to the updated code here to keep a stable branch?

**Comment by pickxiguapi** [comment]
H, thanks for the correction! We have found that updates from the commit `76f8142` do cause conflicts, we have located the error and will complete the fix **in two days**. By the way, we are working on improving unit tests coverage to ensure that the codebase is stable for version iterations. We sincerely appreciate the correction!

**Comment by pickxiguapi** [comment]
Hi, we have fixed the no condition error now. Close the issue and feel free to reopen it.
