### ISSUE TITLE
如何接入自己采集的真实数据？

### ISSUE THREAD

**Issue by LemonQC** [CleanDiffuserTeam/CleanDiffuser#33]

**Comment by pickxiguapi** [comment]
Good question! We are currently utilizing the CleanDiffuser library for real-robot training, employing a data reader similar to lerobot library. We have made several modifications to ensure compatibility with CleanDiffuser. We are actively working on updating this feature, and it will be available soon.

**Comment by pickxiguapi** [comment]
Close the issue now and feel free to reopen it. By the way, you can check the `lightning` branch to follow the new process, but it may be unstable without testing.
