### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by liaojiaxin97** [CleanDiffuserTeam/CleanDiffuser#34]
你好，我在配置环境时遇到一些问题：
1.安装mujoco相关依赖我是按照新用户使用pip install mujoco还是按照2.1二进制版本安装呢？

![image](https://github.com/user-attachments/assets/e251022e-e7b6-4305-a1a0-b51e8a0766dc)
我使用了二进制版本安装
![image](https://github.com/user-attachments/assets/aa9fba67-a854-4c3b-94f5-e369b421c125)
2.对于d4rl，这里我是使用pip install -e .安装老版本还是通过pip install gymnasium安装新版本呢？按照mujoco的安装版本这里我应该按照前者安装（不确定？）
![image](https://github.com/user-attachments/assets/d66bf4a5-db12-4144-bb83-0e5f73cdd1b2)
![1730790242324](https://github.com/user-attachments/assets/4821f5fe-ed69-46bc-ab90-41e0b0f2b4e2)
安装后运行tutorials里的代码，这里导入d4rl有对应的v3版本吗?我运行后告诉我不存在v3版本的Fetch，另外如果要使用v3版本，我是否应该通过import gymnasium as gym导入呢？
![image](https://github.com/user-attachments/assets/6b383bc2-8040-4c29-aa91-9a606de2b5fe)

**Comment by pickxiguapi** [comment]
你好，CleanDiffuser的Offline RL算法部分主要基于主流使用的d4rl库和对应的数据集，d4rl一般使用mujoco210的mujoco版本以及V2版本的mujoco环境，详细安装方法和注意事项可以参考d4rl的readme。

我将关闭这个issue，如果你有任何新的问题，欢迎重新打开或发起新的issue！

**Comment by simon7073** [comment]
我希望再次打开这个话题，因为目前的软件包之间存在不可调和的依赖冲突：

D4RL 依赖于 mjrl包， mjrl 要求
python =3.7
pytorch ==1.4
gym ==0.13
但是 CleanDiffuser@0.1.0 要求
python	==3.9
pytorch	==2.2.2
gym	==0.21.0

robosuite@v1.5.1 要求
mujoco >=3.2.3
但是 CleanDiffuser@0.1.0 要求
mujoco <=3.1.6
(这个版本冲突似乎可以将robosuite 降版本为 v1.4.0，至少看起来可以解决，我一直没有运行起来)
