### ISSUE TITLE
训练相关问题

### ISSUE THREAD

**Issue by liaojiaxin97** [CleanDiffuserTeam/CleanDiffuser#36]
1）请问这里的训练步长是多少？这种检查点是需在代码里额外编写吗？
![image](https://github.com/user-attachments/assets/960acfbb-8cf6-413f-85de-83f17cdfdaa6)
2）我训练运行pipeline中的代码，生成wandb文件夹，每次通过wandb sync ……同步到云端，能不能每次训练完直接在云端显示，不用手动同步

**Comment by pickxiguapi** [comment]
1、训练步数均为1M，获取ckpt可以修改config里面的save_freq，每save_freq步保存一次ckpt
2、config参数中的wandb_mode默认为offline，即不同步数据到云端，改成online即可自动同步

如果有任何新的问题，欢迎重新打开这个issue!

**Comment by liaojiaxin97** [comment]
十分感谢！
