### ISSUE TITLE
A question about dd_antmaze.py

### ISSUE THREAD

**Issue by HenryZhang-git** [CleanDiffuserTeam/CleanDiffuser#38]
Hi,bro, good job!

But when i run this code `python .\pipelines\dd_d4rl_antmaze.py task=antmaze-medium-diverse-v2 mode=train`, the error is coming:
`Error executing job with overrides: ['task=antmaze-medium-diverse-v2', 'mode=train']
Traceback (most recent call last):
  File "C:\Users\33908\Desktop\Code\CleanDiffuser-main\pipelines\dd_d4rl_antmaze.py", line 89, in pipeline
    if n_gradient_step <= args.classifier_gradient_steps:
omegaconf.errors.ConfigAttributeError: Key 'classifier_gradient_steps' is not in struct
    full_key: classifier_gradient_steps
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.`

Maybe we should change the `classifier_gradient_steps`  to `invdyn_gradient_steps` ???

**Comment by pickxiguapi** [comment]
Thanks for pointing that out! After double-checking, I realized that you were right, and I'll fix that little mistake right away!
