### ISSUE TITLE
About dm_control and mujoco version compatibility

### ISSUE THREAD

**Issue by RongXueZoe** [CleanDiffuserTeam/CleanDiffuser#8]
Hi! When I encountered an error when running tutorial 1 `1_a_minimal_DBC_implementation.py`: 
`File "/home/xxxxx/mambaforge/envs/cleandiffuser/lib/python3.9/site-packages/dm_control/mujoco/index.py", line 629, in struct_indexer
    attr = getattr(struct, field_name)
AttributeError: 'MjModel' object has no attribute 'eq_active'`

I found that it was because the dm_control pkg automatically installed mujoco==3.1.6 and it's not compatible with mujoco-py==2.1.6. It should work by `pip install mujoco==2.3.1.post1` after running `pip install -r requirements/req_il.txt`. 

Although the script is running now, please let me know if the pkg version is wrong. Thanks a lot!

**Comment by pickxiguapi** [comment]
Thanks, we will reproduce the issue as soon as possible. In my knowledge, I don't think the version of mujoco will cause a change in the experimental results as long as the experiment works :)

**Comment by RongXueZoe** [comment]
> Thanks, we will reproduce the issue as soon as possible. In my knowledge, I don't think the version of mujoco will cause a change in the experimental results as long as the experiment works :)

I see. Thanks for your reply;)

**Comment by ZibinDong** [comment]
I have just updated the requirements and installation instructions. The new installation process has been tested and shown to work without conflicts across all **RL** and **IL** environments. If you encounter any further conflict issues, consider reinstalling following the new installation instructions. I will close the issue for now, but feel free to reopen it.
